[build]
  command = "npm install -g @angular/cli && npm install && ng build --configuration production"
  publish = "dist/emp-data/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
